apiVersion: apps/v1 
kind:  Deployment
metadata:
  namespace: nginx-ns 
  name: nginx-deploy 
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx

  replicas: 5

  template:
    metadata:
      name:  nginx
      labels:
        app: nginx
        name: nginx
        type: frontend 
    spec:   
      containers:
        - name:  nginx
          image:  nginx:1.9.2
          env:
            - name:  "DEVELOPPER_TEAM"
              value: "Wari Dev Team"
